# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the master branch
# on:
#   push:
#     branches: [ vlogmap ]
#   pull_request:
#     branches: [ vlogmap ]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
    
#     strategy:
#       matrix:
#         node-version: [10.x]

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
# #     - name: Run a one-line script
# #       run: echo Hello, world!

# #     # Runs a set of commands using the runners shell
# #     - name: Run a multi-line script
# #       run: |
# #         echo Add other actions to build,
# #         echo test, and deploy your project.

#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm install --verbose --no-optional
#     - run: npm run build --if-present --silent
# #     - run: npm test
#       env:
#         CI: false

#     - name: deploy-via-scp
#       uses: horochx/deploy-via-scp@v1.0.1
#       with:
#         local: ./build # eg: dist
#         remote: ${{ secrets.REMOTE }} # eg: /home/github-action
#         host: ${{ secrets.HOST }} # eg: example.com
#         port: ${{ secrets.PORT }} # eg: 22
#         user: ${{ secrets.USER }} # eg: github-action
#         key: ${{ secrets.KEY }}
name: MapCI

on:
  push:
    branches:
      - vlogmap

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm i --no-optional
      - run: npm run build
      
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./build/*
          host: ${{ secrets.HOST }}
          remote: ${{ secrets.REMOTE }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
